FROM python:3.9.7-alpine

ENV PYTHONUNBUFFERED True

RUN apk update && apk add gcc libc-dev make sqlite-dev git perl \
    && git clone --recursive https://github.com/epoz/fts5-snowball.git

WORKDIR /fts5-snowball

RUN make

COPY ./data /data
COPY ./src/scripts/make_index.py /data/

RUN cp /fts5-snowball/fts5stemmer.so /usr/local/lib/

WORKDIR /data

RUN pip install textbase xlsxwriter tqdm

CMD python make_index.py
